2024-12-08 08:28:25,348:DEBUG:certbot._internal.main:certbot version: 3.0.1
2024-12-08 08:28:25,348:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-12-08 08:28:25,348:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'tbongkim03@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'parkingissue.online']
2024-12-08 08:28:25,348:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-12-08 08:28:25,359:DEBUG:certbot._internal.log:Root logging level set at 30
2024-12-08 08:28:25,361:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-12-08 08:28:25,361:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f1a26e01370>
Prep: True
2024-12-08 08:28:25,361:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f1a26e01370> and installer None
2024-12-08 08:28:25,361:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-12-08 08:28:25,407:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2100863967', new_authzr_uri=None, terms_of_service=None), 9c1f5364519649d68a1e048dbf4abd52, Meta(creation_dt=datetime.datetime(2024, 12, 8, 8, 21, 33, tzinfo=<UTC>), creation_host='fc45881219b9', register_to_eff=None))>
2024-12-08 08:28:25,407:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-12-08 08:28:25,409:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-12-08 08:28:25,941:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-12-08 08:28:25,941:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:28:25 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "3_8TFp0Ag9s": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-12-08 08:28:25,942:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for parkingissue.online
2024-12-08 08:28:25,947:DEBUG:acme.client:Requesting fresh nonce
2024-12-08 08:28:25,947:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-12-08 08:28:26,125:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-12-08 08:28:26,126:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:28:26 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: MMy3dIC6AhpaPCUTMearwcLMuLWlmjJX3ELvXSqk6ZvQFGHYQuE
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-12-08 08:28:26,127:DEBUG:acme.client:Storing nonce: MMy3dIC6AhpaPCUTMearwcLMuLWlmjJX3ELvXSqk6ZvQFGHYQuE
2024-12-08 08:28:26,127:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "parkingissue.online"\n    }\n  ]\n}'
2024-12-08 08:28:26,129:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJNTXkzZElDNkFocGFQQ1VUTWVhcndjTE11TFdsbWpKWDNFTHZYU3FrNlp2UUZHSFlRdUUiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "nqZPuX1OHiXhULgLpp9vz6et_RhVJgfvOMX1Vuq9cA3kK6J4LKwBkLEZXv9T54r6Wci6plhwKFX1K4A1s0g2mca1yAGNf25N_yXd4Iqjx3s63cZzLsBoSudF-9jZit38kFILo82lPAi9dY2yLzVM8tVFTz_u61wAvuq597-7i8xYHRsuVfiNgiNp3awrgWUMtlFXvTlBYu0dqBvd-c7u5AUtSFQ7QDiKvjyicmRLJ1U-aXYQsUAeAPP3nxpXD5S4ea_3zj9WIdFfxesXVGt3l2ZO6-FptG8jCKvk1rUsZ2xbxHcjcmOMKWsRXj7fTRFd0GB-8xLdVoot8-VUMqtcjg",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInBhcmtpbmdpc3N1ZS5vbmxpbmUiCiAgICB9CiAgXQp9"
}
2024-12-08 08:28:26,326:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 353
2024-12-08 08:28:26,327:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 08 Dec 2024 08:28:26 GMT
Content-Type: application/json
Content-Length: 353
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2100863967/331065990157
Replay-Nonce: MMy3dIC6B8EoWFOD6B5wNdhcLtz050f_nB4vZlKIA8xW2I3BliQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-12-15T08:28:26Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "parkingissue.online"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441679980717"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2100863967/331065990157"
}
2024-12-08 08:28:26,327:DEBUG:acme.client:Storing nonce: MMy3dIC6B8EoWFOD6B5wNdhcLtz050f_nB4vZlKIA8xW2I3BliQ
2024-12-08 08:28:26,327:DEBUG:acme.client:JWS payload:
b''
2024-12-08 08:28:26,328:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441679980717:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJNTXkzZElDNkI4RW9XRk9ENkI1d05kaGNMdHowNTBmX25CNHZabEtJQTh4VzJJM0JsaVEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxMDA4NjM5NjcvNDQxNjc5OTgwNzE3In0",
  "signature": "lmz6V0bVAKH25FlrOG5CSOFUnLNYXeKKRqnUDLKHTCon0RqrHkbrv7RT5ZKzpKt3EyKUpSnKsrA7YmgIE1vzu8rfOdASodW-M2Q5WG43w8asZWq5EluqqVMAlHH3cwkpgp43djYPGJp8YuImLFAavnlgXKzi4z8PpsiJ6n5A-mg7Zk45IpvVjqBEXYjlyUF1uzate6VrLq2WlGM8oR3IHCnOntXfzFx1lXLaxatrTdw_RR8xWAvanHpRSwf88RUiH8Bbs3gP--VbUgeHU-9JhhRCgaTxDoZjmEXRMxRK57QBkCnDKkJcbiOZgE2J5PKIq3exHd2y1WMVW2u4P5t0yw",
  "payload": ""
}
2024-12-08 08:28:26,508:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2100863967/441679980717 HTTP/1.1" 200 827
2024-12-08 08:28:26,508:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:28:26 GMT
Content-Type: application/json
Content-Length: 827
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: MMy3dIC6eV_1JoHs4HZ3xrGmIhTP3HZV9UbEpZ9aBiZzSjx4G7U
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "parkingissue.online"
  },
  "status": "pending",
  "expires": "2024-12-15T08:28:26Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/8fr1pw",
      "status": "pending",
      "token": "_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/XFx8cw",
      "status": "pending",
      "token": "_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/X7W-bQ",
      "status": "pending",
      "token": "_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k"
    }
  ]
}
2024-12-08 08:28:26,509:DEBUG:acme.client:Storing nonce: MMy3dIC6eV_1JoHs4HZ3xrGmIhTP3HZV9UbEpZ9aBiZzSjx4G7U
2024-12-08 08:28:26,509:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-12-08 08:28:26,509:INFO:certbot._internal.auth_handler:http-01 challenge for parkingissue.online
2024-12-08 08:28:26,509:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-12-08 08:28:26,509:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-12-08 08:28:26,510:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k
2024-12-08 08:28:26,511:DEBUG:acme.client:JWS payload:
b'{}'
2024-12-08 08:28:26,512:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/XFx8cw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJNTXkzZElDNmVWXzFKb0hzNEhaM3hyR21JaFRQM0haVjlVYkVwWjlhQmlaelNqeDRHN1UiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIxMDA4NjM5NjcvNDQxNjc5OTgwNzE3L1hGeDhjdyJ9",
  "signature": "UmkRTytn2OIqWQ6_QLAmDxY37cJ4ebSZgGRQmt90SuhtNkPkb-XhkksX8Nd1G0TCeKuAuk2m7UUmGGd_Az83MF58A9m4AY0uQpLAjTDxkJ25r4zucxj0fGWLMQ5paCUiozT3b3SZ3qbm8w4N3Qormc2-fBwwizDYGclfXsThFs77GR3_fngnkgGyjH35SRxFK1BDBh88xJ2gjp7Bvd1yFK0LXojpRzCc77aypn4Si6Ih1dSjTe08RNTxSbeW8AkklJmxRsMDcmBAtclj_MF3Z4JHO5Mqpy-C99Rlod2GcqO2-MPCMcSwGCV7AfB5c-mTBTJXONqDeO0rcb9EOJrV7A",
  "payload": "e30"
}
2024-12-08 08:28:26,692:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2100863967/441679980717/XFx8cw HTTP/1.1" 200 195
2024-12-08 08:28:26,693:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:28:26 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441679980717>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/XFx8cw
Replay-Nonce: qM6CNfq-_8WvBX5-nsq_1Qw9QYIoGbwlWaRpXhYPJsg55mEcP4A
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/XFx8cw",
  "status": "pending",
  "token": "_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k"
}
2024-12-08 08:28:26,693:DEBUG:acme.client:Storing nonce: qM6CNfq-_8WvBX5-nsq_1Qw9QYIoGbwlWaRpXhYPJsg55mEcP4A
2024-12-08 08:28:26,694:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-12-08 08:28:27,694:DEBUG:acme.client:JWS payload:
b''
2024-12-08 08:28:27,695:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441679980717:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJxTTZDTmZxLV84V3ZCWDUtbnNxXzFRdzlRWUlvR2J3bFdhUnBYaFlQSnNnNTVtRWNQNEEiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxMDA4NjM5NjcvNDQxNjc5OTgwNzE3In0",
  "signature": "RjHgppKivAAsKXpCGgT_BwVyz5wZ60fxZFXph_7nl4ZSXr1H-eGYXcj2m_jSUrJRdJTQ_AoZX5PwngkT9WvsRBvKmtcGmVQF0q7UmUktA-xBe7g0cNUHvcFVqLSJeZm95cHMfziBorZvF4BzrXcjU9EU6ARQMkhszHoU6oQGfVuKWxNRUsIeGwgaH0bMS2oEj_n_1rmg4FUHDbnVuhh2ooJGQfv8QdORaVVmW3EZE2E3yD9c0ExvkDdnY_uUifVAYtgUY73ZyyQI6RkQJdeZRQL01XJJoWKNRbYBFsvJszsIPgBvL6rh-Lz123PScFW0-ZhxXaokF-lzBAYM8VEeNw",
  "payload": ""
}
2024-12-08 08:28:27,877:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2100863967/441679980717 HTTP/1.1" 200 1046
2024-12-08 08:28:27,877:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:28:27 GMT
Content-Type: application/json
Content-Length: 1046
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: qM6CNfq-pe0lK2mvJIPpNhT4gEARaizmix99G9WOJ7sGKjXeJRw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "parkingissue.online"
  },
  "status": "invalid",
  "expires": "2024-12-15T08:28:26Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441679980717/XFx8cw",
      "status": "invalid",
      "validated": "2024-12-08T08:28:26Z",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "3.37.20.117: Invalid response from http://parkingissue.online/.well-known/acme-challenge/_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k: 404",
        "status": 403
      },
      "token": "_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k",
      "validationRecord": [
        {
          "url": "http://parkingissue.online/.well-known/acme-challenge/_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k",
          "hostname": "parkingissue.online",
          "port": "80",
          "addressesResolved": [
            "3.37.20.117"
          ],
          "addressUsed": "3.37.20.117"
        }
      ]
    }
  ]
}
2024-12-08 08:28:27,877:DEBUG:acme.client:Storing nonce: qM6CNfq-pe0lK2mvJIPpNhT4gEARaizmix99G9WOJ7sGKjXeJRw
2024-12-08 08:28:27,878:INFO:certbot._internal.auth_handler:Challenge failed for domain parkingissue.online
2024-12-08 08:28:27,878:INFO:certbot._internal.auth_handler:http-01 challenge for parkingissue.online
2024-12-08 08:28:27,878:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: parkingissue.online
  Type:   unauthorized
  Detail: 3.37.20.117: Invalid response from http://parkingissue.online/.well-known/acme-challenge/_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k: 404

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-12-08 08:28:27,879:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-12-08 08:28:27,879:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-12-08 08:28:27,879:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-12-08 08:28:27,879:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/_72Bt3gjpy7f1-KXTEyj4llvcxFmLARu9fFcyzsDy1k
2024-12-08 08:28:27,879:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-12-08 08:28:27,879:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1876, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1578, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-12-08 08:28:27,881:ERROR:certbot._internal.log:Some challenges have failed.
