2024-12-08 08:21:41,984:DEBUG:certbot._internal.main:certbot version: 3.0.1
2024-12-08 08:21:41,984:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-12-08 08:21:41,984:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'tbongkim03@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'parkingissue.online']
2024-12-08 08:21:41,985:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-12-08 08:21:41,995:DEBUG:certbot._internal.log:Root logging level set at 30
2024-12-08 08:21:41,997:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-12-08 08:21:41,997:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x7f24fee0c920>
Prep: True
2024-12-08 08:21:41,998:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x7f24fee0c920> and installer None
2024-12-08 08:21:41,998:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-12-08 08:21:42,042:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2100863967', new_authzr_uri=None, terms_of_service=None), 9c1f5364519649d68a1e048dbf4abd52, Meta(creation_dt=datetime.datetime(2024, 12, 8, 8, 21, 33, tzinfo=<UTC>), creation_host='fc45881219b9', register_to_eff=None))>
2024-12-08 08:21:42,042:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-12-08 08:21:42,044:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-12-08 08:21:42,570:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-12-08 08:21:42,571:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:21:42 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "e1lLLE78f0Q": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-12-08 08:21:42,572:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for parkingissue.online
2024-12-08 08:21:42,581:DEBUG:acme.client:Requesting fresh nonce
2024-12-08 08:21:42,581:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-12-08 08:21:42,758:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-12-08 08:21:42,758:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:21:42 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: vyQW5O6tYV9phIMnalkDG-fH-Y1y-a3IFOAUAgtulKau0viGyfc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-12-08 08:21:42,758:DEBUG:acme.client:Storing nonce: vyQW5O6tYV9phIMnalkDG-fH-Y1y-a3IFOAUAgtulKau0viGyfc
2024-12-08 08:21:42,759:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "parkingissue.online"\n    }\n  ]\n}'
2024-12-08 08:21:42,761:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJ2eVFXNU82dFlWOXBoSU1uYWxrREctZkgtWTF5LWEzSUZPQVVBZ3R1bEthdTB2aUd5ZmMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "Q9e7ZY7Lilm6ZEyE0CcFAutE6JGnQgbAHNZbpXtwIQulL1pKV3fPFW1BWw8SsXsmpg8SjR2jGmKpdpuimBt9de6mT1xl4uy0s8V_w4lYCJVnm-QMmTit9fmV5jcTdopvLYyaWSKeaUHzXwkHVSRTfpeiDjtn0rnBf3QFLuEKv4EsZ0KlNH3zkyxnKxv91O7YRtsHNbS_kpLO0m8eX6RdIsln1Od5msK9sbFE1WmjS2TIQwLMWMCPhCaBFqbHzBuLG88ahAsRFiE5kYNK4EXAsKnUYPKYiylav7KUTR0Sz29-4iL24y9WMZxZC14pnDqw_M-hehGRzdaFodDbruc_Uw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInBhcmtpbmdpc3N1ZS5vbmxpbmUiCiAgICB9CiAgXQp9"
}
2024-12-08 08:21:43,068:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 353
2024-12-08 08:21:43,068:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 08 Dec 2024 08:21:42 GMT
Content-Type: application/json
Content-Length: 353
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2100863967/331064376457
Replay-Nonce: vyQW5O6texSV7afSMHTov-CmCSs6sXCUtJex_W9m6Z1LyxQhNG4
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-12-15T08:21:42Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "parkingissue.online"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677618147"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2100863967/331064376457"
}
2024-12-08 08:21:43,068:DEBUG:acme.client:Storing nonce: vyQW5O6texSV7afSMHTov-CmCSs6sXCUtJex_W9m6Z1LyxQhNG4
2024-12-08 08:21:43,069:DEBUG:acme.client:JWS payload:
b''
2024-12-08 08:21:43,070:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677618147:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJ2eVFXNU82dGV4U1Y3YWZTTUhUb3YtQ21DU3M2c1hDVXRKZXhfVzltNloxTHl4UWhORzQiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxMDA4NjM5NjcvNDQxNjc3NjE4MTQ3In0",
  "signature": "jfVJWtu--ejPi5TmSucEZ7tWPjIEC59qfzAzDPeUv56apwccf0yWwLw8OM7K0trEmxdN4jkZjU3MtG1sz8E3SS4yKdEGpZ0Ruf9M3v6QftLkDRrpT7jcBu9JW9tkNzh670K4VG3UV3DX3X58dIJ7wcRudViVNnHA4i28nSoDFqNCu5GXcbwFX8kYqVptk5tuLVeU--7UxJhl-I861ciAhJssSmd4OPOV0qXx46D6s-K_QifYVoUqbmCOCUp5VrW6lM2LfTJFZTZUw_01qW0Za_QyuYtudU6IIhiuWkpmMijIdHvW7_RyrvcLR_HkgRpsBAJhwj0Ggeb1yanGWiI0Bg",
  "payload": ""
}
2024-12-08 08:21:43,253:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2100863967/441677618147 HTTP/1.1" 200 827
2024-12-08 08:21:43,253:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:21:43 GMT
Content-Type: application/json
Content-Length: 827
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: vyQW5O6t2lRdXd-gjyJCBzANz_qTS4ugZQUYIb2yPKHmOmA4pEk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "parkingissue.online"
  },
  "status": "pending",
  "expires": "2024-12-15T08:21:42Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/xeSSgQ",
      "status": "pending",
      "token": "7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA"
    },
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/FN9Muw",
      "status": "pending",
      "token": "7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/FydAYg",
      "status": "pending",
      "token": "7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA"
    }
  ]
}
2024-12-08 08:21:43,253:DEBUG:acme.client:Storing nonce: vyQW5O6t2lRdXd-gjyJCBzANz_qTS4ugZQUYIb2yPKHmOmA4pEk
2024-12-08 08:21:43,254:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-12-08 08:21:43,254:INFO:certbot._internal.auth_handler:http-01 challenge for parkingissue.online
2024-12-08 08:21:43,254:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-12-08 08:21:43,254:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-12-08 08:21:43,256:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA
2024-12-08 08:21:43,256:DEBUG:acme.client:JWS payload:
b'{}'
2024-12-08 08:21:43,258:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/FN9Muw:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJ2eVFXNU82dDJsUmRYZC1nanlKQ0J6QU56X3FUUzR1Z1pRVVlJYjJ5UEtIbU9tQTRwRWsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIxMDA4NjM5NjcvNDQxNjc3NjE4MTQ3L0ZOOU11dyJ9",
  "signature": "iJRTyBoKGKLN1r0typdI1Sp7MAZERFgmQk1JWLJJp5zqUh3whNDHk7FOQaSmSHZzqsH7nQx75ry0hjUWUE_y7c8PmgPaWR2OeKDwzP6R86deFOGFJFWDJ7-Lnp5Tu8YHm38UIqJGRhEaaVbcbjeQoBcmL8E8JRYxhn6WcgxzARbQ24GDkSJT_4jTOBmMc_lmskRpdKzfzF56Eaf7wIH_Sxf4ugoP0NXJ99IltmeUg9GkLlPdV_wyk_cr9JHUH03hmsdbL6lo1xYQY1QQT5-G1K4nOV209KEct2xHB48efZjSe28ykyk5v28A8DBJuGPrsV4iATwwy2j0LMHcazSKYg",
  "payload": "e30"
}
2024-12-08 08:21:43,441:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2100863967/441677618147/FN9Muw HTTP/1.1" 200 195
2024-12-08 08:21:43,442:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:21:43 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677618147>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/FN9Muw
Replay-Nonce: Uqfi4YotxQabe8zQ6eqtg5h6Glhmln5PwPNaySnostHl_ej9lRc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/FN9Muw",
  "status": "pending",
  "token": "7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA"
}
2024-12-08 08:21:43,442:DEBUG:acme.client:Storing nonce: Uqfi4YotxQabe8zQ6eqtg5h6Glhmln5PwPNaySnostHl_ej9lRc
2024-12-08 08:21:43,443:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-12-08 08:21:44,443:DEBUG:acme.client:JWS payload:
b''
2024-12-08 08:21:44,444:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677618147:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJVcWZpNFlvdHhRYWJlOHpRNmVxdGc1aDZHbGhtbG41UHdQTmF5U25vc3RIbF9lajlsUmMiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxMDA4NjM5NjcvNDQxNjc3NjE4MTQ3In0",
  "signature": "hUy70hVdjcZ0A-mrxcxOjkTCpYRcCxM0CNvM7R5l0x1X13PeI7jT2Gq-qbIbQT9UXJ5ZakPZQUGYJVjuSUfepOULoXOjv3rmyC0bWL0UkqAQLTYWAilImjaQqJtuEPhEuv2O8W5SY1jRqB9hWMWUzCB6FSXMvE8G796PopIL5V7p9EiCSc_AKgybomBvtynBMmYfTq1wnJbyyjtYqaXuZduA7o6HHW-Py5qwflaLeCrJmubk8p2IcyDxFFNNP8r45B_LJ-ufMO3oRuKrkeMAjddM1sKBFG_4A_t2NMM7mLDTX2MbqA8N5GjXHsySGTwqNzjq5AvKnwX4LTz-y99ZBA",
  "payload": ""
}
2024-12-08 08:21:44,623:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2100863967/441677618147 HTTP/1.1" 200 1046
2024-12-08 08:21:44,624:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:21:44 GMT
Content-Type: application/json
Content-Length: 1046
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: vyQW5O6tRdB1V3g221FTLxUPp476cOyT_QvMxcbgukXnwq5YUpc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "parkingissue.online"
  },
  "status": "invalid",
  "expires": "2024-12-15T08:21:42Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677618147/FN9Muw",
      "status": "invalid",
      "validated": "2024-12-08T08:21:43Z",
      "error": {
        "type": "urn:ietf:params:acme:error:unauthorized",
        "detail": "3.37.20.117: Invalid response from http://parkingissue.online/.well-known/acme-challenge/7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA: 404",
        "status": 403
      },
      "token": "7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA",
      "validationRecord": [
        {
          "url": "http://parkingissue.online/.well-known/acme-challenge/7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA",
          "hostname": "parkingissue.online",
          "port": "80",
          "addressesResolved": [
            "3.37.20.117"
          ],
          "addressUsed": "3.37.20.117"
        }
      ]
    }
  ]
}
2024-12-08 08:21:44,624:DEBUG:acme.client:Storing nonce: vyQW5O6tRdB1V3g221FTLxUPp476cOyT_QvMxcbgukXnwq5YUpc
2024-12-08 08:21:44,624:INFO:certbot._internal.auth_handler:Challenge failed for domain parkingissue.online
2024-12-08 08:21:44,624:INFO:certbot._internal.auth_handler:http-01 challenge for parkingissue.online
2024-12-08 08:21:44,624:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: parkingissue.online
  Type:   unauthorized
  Detail: 3.37.20.117: Invalid response from http://parkingissue.online/.well-known/acme-challenge/7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA: 404

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-12-08 08:21:44,625:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-12-08 08:21:44,625:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-12-08 08:21:44,625:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-12-08 08:21:44,626:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/7de5yTtWfO3TqGgZhaJB7kuRLBxmXcbIaEQzpuG7bbA
2024-12-08 08:21:44,626:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-12-08 08:21:44,626:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1876, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1578, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-12-08 08:21:44,628:ERROR:certbot._internal.log:Some challenges have failed.
