2024-12-08 08:22:33,662:DEBUG:certbot._internal.main:certbot version: 3.0.1
2024-12-08 08:22:33,663:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/local/bin/certbot
2024-12-08 08:22:33,663:DEBUG:certbot._internal.main:Arguments: ['--webroot', '--webroot-path=/var/www/certbot', '--email', 'tbongkim03@gmail.com', '--agree-tos', '--no-eff-email', '-d', 'parkingissue.online']
2024-12-08 08:22:33,663:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-12-08 08:22:33,680:DEBUG:certbot._internal.log:Root logging level set at 30
2024-12-08 08:22:33,684:DEBUG:certbot._internal.plugins.selection:Requested authenticator webroot and installer None
2024-12-08 08:22:33,684:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * webroot
Description: Saves the necessary validation files to a .well-known/acme-challenge/ directory within the nominated webroot path. A separate HTTP server must be running and serving files from the webroot path. HTTP challenge only (wildcards not supported).
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='webroot', value='certbot._internal.plugins.webroot:Authenticator', group='certbot.plugins')
Initialized: <certbot._internal.plugins.webroot.Authenticator object at 0x78ff2fe91880>
Prep: True
2024-12-08 08:22:33,685:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.webroot.Authenticator object at 0x78ff2fe91880> and installer None
2024-12-08 08:22:33,685:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator webroot, Installer None
2024-12-08 08:22:33,761:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/2100863967', new_authzr_uri=None, terms_of_service=None), 9c1f5364519649d68a1e048dbf4abd52, Meta(creation_dt=datetime.datetime(2024, 12, 8, 8, 21, 33, tzinfo=<UTC>), creation_host='fc45881219b9', register_to_eff=None))>
2024-12-08 08:22:33,762:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-12-08 08:22:33,764:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-12-08 08:22:34,277:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/1.1" 200 746
2024-12-08 08:22:34,278:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:22:34 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "q8uhErwKHKg": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-12-08 08:22:34,279:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for parkingissue.online
2024-12-08 08:22:34,291:DEBUG:acme.client:Requesting fresh nonce
2024-12-08 08:22:34,292:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-12-08 08:22:34,469:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/1.1" 200 0
2024-12-08 08:22:34,470:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:22:34 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: qM6CNfq-NFltAdKqD7AFumrwzexVKwNqBLimgCISTemWZEb2Bww
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-12-08 08:22:34,470:DEBUG:acme.client:Storing nonce: qM6CNfq-NFltAdKqD7AFumrwzexVKwNqBLimgCISTemWZEb2Bww
2024-12-08 08:22:34,470:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "parkingissue.online"\n    }\n  ]\n}'
2024-12-08 08:22:34,476:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJxTTZDTmZxLU5GbHRBZEtxRDdBRnVtcnd6ZXhWS3dOcUJMaW1nQ0lTVGVtV1pFYjJCd3ciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL25ldy1vcmRlciJ9",
  "signature": "I0tGdedK8px7YZmuQ_NI3lRD7lBbLZemOxbBMrdC3xoev9cBmJzJ_xxQ1xODSZI6gSx1RrOzp4ye2kV2ptxAg4cr8Tpsfs53nizqhsmZ1Oz3dlSeTT2ZToog1xVr62jHobnq-U_5oSVS7YRXEfAbYFDelKaQnJ8NKKX_nu29zqwSbP0uwOJXwntZMwQEHGT8azFGa40O17hyz4sqZVylOSxP2eyC_pt1hjEvMiGOjRWDSHkH92WgyGfguFTlJkAn6NxymoZb9VvniuASKJhXrFJtFvss1g_gZFss5c91Sq4jX2caSNGjJ3TTjDgv2IELog1JqpwQHBBjDwC820jpTw",
  "payload": "ewogICJpZGVudGlmaWVycyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiZG5zIiwKICAgICAgInZhbHVlIjogInBhcmtpbmdpc3N1ZS5vbmxpbmUiCiAgICB9CiAgXQp9"
}
2024-12-08 08:22:34,672:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/1.1" 201 353
2024-12-08 08:22:34,674:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sun, 08 Dec 2024 08:22:34 GMT
Content-Type: application/json
Content-Length: 353
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/2100863967/331064586707
Replay-Nonce: MMy3dIC6DO5qQyu7z7hCwS_ss85lN-NymYKhFHVWY3IXVH03Frk
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2024-12-15T08:22:34Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "parkingissue.online"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677925937"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/2100863967/331064586707"
}
2024-12-08 08:22:34,675:DEBUG:acme.client:Storing nonce: MMy3dIC6DO5qQyu7z7hCwS_ss85lN-NymYKhFHVWY3IXVH03Frk
2024-12-08 08:22:34,676:DEBUG:acme.client:JWS payload:
b''
2024-12-08 08:22:34,680:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677925937:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJNTXkzZElDNkRPNXFReXU3ejdoQ3dTX3NzODVsTi1OeW1ZS2hGSFZXWTNJWFZIMDNGcmsiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxMDA4NjM5NjcvNDQxNjc3OTI1OTM3In0",
  "signature": "ZliYpkbI-NDoj_AuCDt98Z6bcQ3qmOWahiHGChO46rkkrHLLhtvQfvjORiZIrHMvmKyNc870GSalO8nF7w4z-H74b-qZHQoPABQixsuRYqbjzeKUFEgd9asVo4aaajRUDQ-kcQZAyjlpS-7fBrk3UOUoV3mGMH0-n62b3trU-5g-EOu5fqZMPWaGHLa6jyKQAGJ0wQH0eLe5-UlrcDtOzMoUNLpyTaVMaZA4Z5kn5KQyRZyLWPb8drN-cW1p4MCFDs3p5scR4Fyd9VOt45CTuV6ZHjuZBPAwqndEsJdWk3yvHQLGPxr9x91b4kt0gnBLxBMbXLP2dVo_mcRE8H7gbA",
  "payload": ""
}
2024-12-08 08:22:34,855:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2100863967/441677925937 HTTP/1.1" 200 827
2024-12-08 08:22:34,856:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:22:34 GMT
Content-Type: application/json
Content-Length: 827
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: MMy3dIC6tYc_bV3qzPcvra2LRLm75B7Lwn_iLSQjeheUgLURm-I
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "parkingissue.online"
  },
  "status": "pending",
  "expires": "2024-12-15T08:22:34Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/rCevEg",
      "status": "pending",
      "token": "eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ"
    },
    {
      "type": "tls-alpn-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/vKUySg",
      "status": "pending",
      "token": "eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ"
    },
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/CwMw7g",
      "status": "pending",
      "token": "eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ"
    }
  ]
}
2024-12-08 08:22:34,856:DEBUG:acme.client:Storing nonce: MMy3dIC6tYc_bV3qzPcvra2LRLm75B7Lwn_iLSQjeheUgLURm-I
2024-12-08 08:22:34,856:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-12-08 08:22:34,856:INFO:certbot._internal.auth_handler:http-01 challenge for parkingissue.online
2024-12-08 08:22:34,856:INFO:certbot._internal.plugins.webroot:Using the webroot path /var/www/certbot for all unmatched domains.
2024-12-08 08:22:34,857:DEBUG:certbot._internal.plugins.webroot:Creating root challenges validation dir at /var/www/certbot/.well-known/acme-challenge
2024-12-08 08:22:34,858:DEBUG:certbot._internal.plugins.webroot:Attempting to save validation to /var/www/certbot/.well-known/acme-challenge/eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ
2024-12-08 08:22:34,859:DEBUG:acme.client:JWS payload:
b'{}'
2024-12-08 08:22:34,860:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/rCevEg:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJNTXkzZElDNnRZY19iVjNxelBjdnJhMkxSTG03NUI3THduX2lMU1FqZWhlVWdMVVJtLUkiLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2NoYWxsLzIxMDA4NjM5NjcvNDQxNjc3OTI1OTM3L3JDZXZFZyJ9",
  "signature": "cI_8M39Qded9kKSUcnLKrcPlCMdnSCTyokmoN4SHVEfTePc3vzXKJfXvcTptrveiUoZxOLd0ibpsUl83bjdBIOu3TQTGyaxnZi-v3tO-4cXMHU7rRcoOR4beaDeDlIfiFH8LM-uLwHw163ywRytD7-9W0v25vIYjwjkiuwGyIdajBEjA6-ISnCL6MknkFwzCTUbXyHZoqFK4Fr1AzMm93VHZM3NFBgJBxfwnF70JpMv60lih8GZx-VP31i5dbN370kS9HeHY_YKAMOOl-3MMRRXqdAR2sxDejagP3RGjyNejGB76WRraDqPtxvB4uEzin9VjVJobr4u9PRepDFdkLA",
  "payload": "e30"
}
2024-12-08 08:22:35,036:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/chall/2100863967/441677925937/rCevEg HTTP/1.1" 200 195
2024-12-08 08:22:35,037:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:22:34 GMT
Content-Type: application/json
Content-Length: 195
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index", <https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677925937>;rel="up"
Location: https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/rCevEg
Replay-Nonce: qM6CNfq-FqMPUqnDeXx11VvJHaCzL636C0tj8lv5CTYzviihPQw
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "type": "http-01",
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/rCevEg",
  "status": "pending",
  "token": "eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ"
}
2024-12-08 08:22:35,037:DEBUG:acme.client:Storing nonce: qM6CNfq-FqMPUqnDeXx11VvJHaCzL636C0tj8lv5CTYzviihPQw
2024-12-08 08:22:35,037:INFO:certbot._internal.auth_handler:Waiting for verification...
2024-12-08 08:22:36,038:DEBUG:acme.client:JWS payload:
b''
2024-12-08 08:22:36,043:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/2100863967/441677925937:
{
  "protected": "eyJhbGciOiAiUlMyNTYiLCAia2lkIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2FjY3QvMjEwMDg2Mzk2NyIsICJub25jZSI6ICJxTTZDTmZxLUZxTVBVcW5EZVh4MTFWdkpIYUN6TDYzNkMwdGo4bHY1Q1RZenZpaWhQUXciLCAidXJsIjogImh0dHBzOi8vYWNtZS12MDIuYXBpLmxldHNlbmNyeXB0Lm9yZy9hY21lL2F1dGh6LzIxMDA4NjM5NjcvNDQxNjc3OTI1OTM3In0",
  "signature": "GE2drQTnUY_IGI9yC4LTP7g0MqpU5jDhEQKVtqzybntfDdg0ctbFx_adn9oJrXfp84gdc1CFzJ22PGLLF-Y1t97LqtrDgDfoiicEdEtLlagCxNMVmU7U0TGYGf7UeGqrz71wokZD9H7fHG6eJxVXRmdd8jYMXPiGSvnCOt9nFs_s_2OBUT9xp0m33bKAeQ7xiAFWBS_EuZFLbvJA07DPRYO4BKVqf0i9GsVFpD1d4LGQOBCvp3jwMn41uHsmqAYwdOhrABrtw4tcG53kK8PkUlPdcxi4znTWT5xuopYhunY2Y3MpueO3FKWAbVTbXhf04xUYsMDJwA2aUywEJOSfAg",
  "payload": ""
}
2024-12-08 08:22:36,219:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/2100863967/441677925937 HTTP/1.1" 200 1046
2024-12-08 08:22:36,219:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sun, 08 Dec 2024 08:22:36 GMT
Content-Type: application/json
Content-Length: 1046
Connection: keep-alive
Boulder-Requester: 2100863967
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: MMy3dIC6IstaUxoMEvgQci0cv1S3Fs_I9SrrW0Cg2Zxe_UEw2n8
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "parkingissue.online"
  },
  "status": "invalid",
  "expires": "2024-12-15T08:22:34Z",
  "challenges": [
    {
      "type": "http-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/2100863967/441677925937/rCevEg",
      "status": "invalid",
      "validated": "2024-12-08T08:22:34Z",
      "error": {
        "type": "urn:ietf:params:acme:error:connection",
        "detail": "3.37.20.117: Fetching http://parkingissue.online/.well-known/acme-challenge/eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ: Connection refused",
        "status": 400
      },
      "token": "eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ",
      "validationRecord": [
        {
          "url": "http://parkingissue.online/.well-known/acme-challenge/eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ",
          "hostname": "parkingissue.online",
          "port": "80",
          "addressesResolved": [
            "3.37.20.117"
          ],
          "addressUsed": "3.37.20.117"
        }
      ]
    }
  ]
}
2024-12-08 08:22:36,219:DEBUG:acme.client:Storing nonce: MMy3dIC6IstaUxoMEvgQci0cv1S3Fs_I9SrrW0Cg2Zxe_UEw2n8
2024-12-08 08:22:36,220:INFO:certbot._internal.auth_handler:Challenge failed for domain parkingissue.online
2024-12-08 08:22:36,220:INFO:certbot._internal.auth_handler:http-01 challenge for parkingissue.online
2024-12-08 08:22:36,220:DEBUG:certbot._internal.display.obj:Notifying user: 
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: parkingissue.online
  Type:   connection
  Detail: 3.37.20.117: Fetching http://parkingissue.online/.well-known/acme-challenge/eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ: Connection refused

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.

2024-12-08 08:22:36,221:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.

2024-12-08 08:22:36,221:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-12-08 08:22:36,221:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-12-08 08:22:36,221:DEBUG:certbot._internal.plugins.webroot:Removing /var/www/certbot/.well-known/acme-challenge/eUN4Kcny05Hg979xyLt1FuNo1z6s1aeS1Yo9F8ygVmQ
2024-12-08 08:22:36,221:DEBUG:certbot._internal.plugins.webroot:All challenges cleaned up
2024-12-08 08:22:36,221:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot', 'console_scripts', 'certbot')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1876, in main
    return config.func(config, plugins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 1578, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 108, in handle_authorizations
    self._poll_authorizations(authzrs, max_retries, max_time_mins, best_effort)
  File "/opt/certbot/src/certbot/certbot/_internal/auth_handler.py", line 212, in _poll_authorizations
    raise errors.AuthorizationError('Some challenges have failed.')
certbot.errors.AuthorizationError: Some challenges have failed.
2024-12-08 08:22:36,223:ERROR:certbot._internal.log:Some challenges have failed.
